airline_server/config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :reservations
  resources :planes
  resources :users
  resources :flights
  get 'flights/list/:x/:y/' => 'flights#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

airline_server/app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :flight
  belongs_to :user

  validates :seat, :presence => true, format: { with: /\A[A-Z]\d+\z/, message: "format incorrect. Please enter seat number in the correct format, e.g. A1."}
  validates_uniqueness_of :seat, :scope => [:flight_id] # checks if seat is taken
  validate :seat_limits

  private
  def seat_limits
    unless flight_id == nil
      row = seat[0].ord - 64
      column = seat[1..seat.size].to_i
      plane_rows = self.flight.plane.rows
      plane_columns = self.flight.plane.columns

      if row > plane_rows
        errors.add(:seat, "row doesn't exist. Please capitalize the letter or check the number of rows on the plane for this flight.")
      elsif column < 1
        errors.add(:seat, "column doesn't exist.")
      elsif column > plane_columns
        errors.add(:seat, "column doesn't exist. Check the number of columns on the plane for this flight.")
      end
    end
  end
end

airline_server/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.fetch(:reservation).permit(:seat, :user_id, :flight_id)
    end
end

airline_server/app/helpers/reservations_helper.rb
module ReservationsHelper
end

airline_server/app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :seat %>
    <%= form.text_field :seat, id: :seat %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.order(:name), :id, :name, include_blank: true  %>
  </div>

  <div class="field">
    <%= form.label :flight_id %>
    <%= form.collection_select :flight_id, Flight.order(:flight_number), :id, :flight_number, include_blank: true  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

airline_server/app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

airline_server/app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Flight #</th>
      <th>User</th>
      <th>Seat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.flight.flight_number, flight_url(reservation.flight.id) %></td>
        <td><%= link_to reservation.user.name, user_url(reservation.user.id) %></td>
        <td><%= reservation.seat %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

airline_server/app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

airline_server/app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Reservation Details</h2>

<p>
  <strong>Name:</strong>
  <%= link_to @reservation.user.name, user_path(@reservation.user.id) %>
</p>

<p>
  <strong>Flight Number:</strong>
  <%= link_to @reservation.flight.flight_number, flight_path(@reservation.flight.id) %>
</p>

<p>
  <strong>Departure Date:</strong>
  <%= @reservation.flight.departure_date %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @reservation.flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @reservation.flight.destination %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @reservation.seat %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>