airline_server/config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :reservations
  resources :planes
  resources :users
  resources :flights
  get 'flights/list/:x/:y/' => 'flights#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

airline_server/app/models/plane.rb
class Plane < ApplicationRecord
  has_many :flights
end

airline_server/app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:name, :rows, :columns)
    end
end

airline_server/app/helpers/planes_helper.rb
module PlanesHelper
end

airline_server/app/views/planes/_form.html.erb
<%= form_with(model: plane, local: true) do |form| %>
  <% if plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :plane_name %>
  </div>

  <div class="field">
    <%= form.label :rows %>
    <%= form.text_field :rows, id: :plane_rows %>
  </div>

  <div class="field">
    <%= form.label :columns %>
    <%= form.text_field :columns, id: :plane_colums %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

airline_server/app/views/planes/edit.html.erb
<h1>Editing Plane</h1>

<%= render 'form', plane: @plane %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

airline_server/app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rows</th>
      <th>Cols</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planes.each do |plane| %>
      <tr>
        <td><%= plane.name %></td>
        <td><%= plane.rows %></td>
        <td><%= plane.columns %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plane', new_plane_path %>

airline_server/app/views/planes/new.html.erb
<h1>New Plane</h1>

<%= render 'form', plane: @plane %>

<%= link_to 'Back', planes_path %>

airline_server/app/views/planes/seats.html.erb
<ul>
  <li><%=flight.flight_number%></li>
  <li><%=flight.origin%></li>
  <li><%=flight.destination%></li>
  <li><%=flight.departure_date%></li>
  <li><%=flight.arrival_date%></li>
  <li><%=flight.plane_id%></li>
</ul>

airline_server/app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plane.name %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @plane.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @plane.columns %>
</p>

<p><strong>Seat Map</strong></p>

<div class="seat-map">
  <% @plane.rows.times do %>
    <div>
      <% @plane.columns.times do %>
        <span>O</span>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>