airline_server/config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :reservations
  resources :planes
  resources :users
  resources :flights
  get 'flights/list/:x/:y/' => 'flights#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

airline_server/app/models/flight.rb
class Flight < ApplicationRecord
  has_many :users, through: :reservations
  belongs_to :plane
end

airline_server/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
    @flights_sorted = Flight.all.sort_by # { |f| f.departure_date }
    @flights_sorted_rev = @flights_sorted.reverse_each
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    # @flight = Flight.find_by()
  end

  def list
    @x = params[:x].upcase
    @y = params[:y].upcase
    @flight = Flight.all
  end
  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:flight_number, :origin, :destination, :departure_date, :arrival_date, :plane_id)
    end
end

airline_server/app/helpers/flights_helper.rb
module FlightsHelper
end

airline_server/app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :flight_number %>
    <%= form.text_area :flight_number, :class => "" %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_area :origin %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_area :destination %>
  </div>

  <div class="field">
    <%= form.label :departure_date %>
    <%= form.date_select :departure_date %>
  </div>

  <div class="field">
    <%= form.label :plane_id %>
    <%= form.collection_select :plane_id, Plane.order(:name), :id, :name, include_blank: true  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

airline_server/app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

airline_server/app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Departure Date</th>
      <th>Plane</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights_sorted.each do |flight| %>
      <tr>
        <td><%= flight.flight_number %></td>
        <td><%= flight.origin %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.departure_date %></td>
        <td><%= link_to flight.plane.name, plane_url(flight.plane_id) %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

airline_server/app/views/flights/list.html.erb
<h2>List</h2>
  <% @flight.each do |flight| %>
      <% if flight.origin == @x && flight.destination == @y %>
      <ul>
        <li><%=flight.flight_number%></li>
        <li><%=flight.origin%></li>
        <li><%=flight.destination%></li>
        <li><%=flight.departure_date%></li>
        <li><%=flight.arrival_date%></li>
        <li><%=flight.plane_id%></li>
      </ul>
      <% end %>

<% end %>

airline_server/app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

airline_server/app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @flight.flight_number %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.departure_date %>
</p>

<p>
  <strong>Plane:</strong>
  <%= link_to @flight.plane.name, plane_path(@flight.plane.id) %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>